
[package]
name = "actors"
version = "0.1.0"
edition = "2021"

[dependencies]
ractor = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
core = { path = "../core" }
infra = { path = "../infra" }
types = { path = "../types" }
