
[package]
name = "types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
time = { workspace = true }
secrecy = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }