
[package]
name = "kit"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
reqwest = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }
infra = { path = "../infra" }
core = { path = "../core" }
types = { path = "../types" }
